Integration of vllm service
Signed-off-by: Vellaisamy, Sathyendran <sathyendran.vellaisamy@intel.com>

diff --git a/manufacturing-ai-suite/industrial-edge-insights-multimodal/Makefile b/manufacturing-ai-suite/industrial-edge-insights-multimodal/Makefile
--- a/manufacturing-ai-suite/industrial-edge-insights-multimodal/Makefile
+++ b/manufacturing-ai-suite/industrial-edge-insights-multimodal/Makefile
@@ -196,14 +196,47 @@ post_config:
 .PHONY: up
 up: check_env_variables validate_host_ip down
 	@export TELEGRAF_INPUT_PLUGIN=$$(if [ $(INCLUDE) = 'validation' ]; then echo "mqtt_consumer:net:cpu:disk:docker:diskio:kernel:mem:processes:swap:system"; else echo "mqtt_consumer"; fi); \
+	export NGINX_CONFIG_PATH=./configs/nginx/nginx.conf; \
 	echo "Starting Docker containers..."; \
 	echo "GPU device path set to: $(DRI_MOUNT_PATH) based on its existence"; \
 	if [ $(INCLUDE) = 'validation' ]; then \
 		$(DOCKER_COMPOSE) -f $(DOCKER_COMPOSE_FILE) -f $(DOCKER_COMPOSE_VALIDATION_FILE) up -d; \
 	else \
+		cp configs/grafana/dashboards_jsons/weld_defect_detection.json configs/grafana/provisioning/weld_defect_detection.json; \
 		$(DOCKER_COMPOSE) up -d; \
 	fi; \
 	$(MAKE) upload_tar_file
+
+
+.PHONY: check_models
+check_models:
+	@echo "Checking if vllm models are available..."
+	@for dir in configs/vllm/models; do \
+		if [ ! -d "$$dir" ]; then \
+			echo "Error: $$dir directory does not exist."; \
+			exit 1; \
+		fi; \
+		if [ -z "$$(ls -A $$dir 2>/dev/null)" ]; then \
+			echo "Error: $$dir directory is empty."; \
+			exit 1; \
+		fi; \
+		echo "Models found in $$dir directory."; \
+	done
+
+.PHONY: up_vllm
+up_vllm: check_env_variables validate_host_ip down check_models
+	@export TELEGRAF_INPUT_PLUGIN=$$(if [ $(INCLUDE) = 'validation' ]; then echo "mqtt_consumer:net:cpu:disk:docker:diskio:kernel:mem:processes:swap:system"; else echo "mqtt_consumer"; fi); \
+	export NGINX_CONFIG_PATH=./configs/nginx/nginx_vllm.conf; \
+	echo "Starting Docker containers..."; \
+	echo "GPU device path set to: $(DRI_MOUNT_PATH) based on its existence"; \
+	if [ $(INCLUDE) = 'validation' ]; then \
+		$(DOCKER_COMPOSE) -f $(DOCKER_COMPOSE_FILE) -f $(DOCKER_COMPOSE_VALIDATION_FILE) up -d; \
+	else \
+		cp configs/grafana/dashboards_jsons/weld_defect_detection_vlm.json configs/grafana/provisioning/weld_defect_detection.json; \
+		$(DOCKER_COMPOSE) -f $(DOCKER_COMPOSE_FILE) -f docker-compose-vllm.yml up -d; \
+	fi; \
+	$(MAKE) upload_tar_file
+
 
 # Status of the deployed containers
 .PHONY: status
